apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: piers-walter-own-app-buildah
spec:
  params:
    - default: 'https://github.com/account-name/repo-name'
      description: Source repository name
      name: source-repo
      type: string
    - default: quay.io/account-name/repo-name
      description: Docker image name
      name: image-repo
      type: string
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: 'https://github.com/piers-walter-ibm/bootcamp-own-app'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data

    - name: build-image
      params:
        - name: IMAGE
          value: >-
            quay.io/piers_walter_ibm/own-app:$(tasks.clone-repository.results.commit)
      runAfter:
        - clone-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data

    - name: kustomize-build
      runAfter:
        - build-image
      params:
        - name: app-namespace
          value: <namespace>
        - name: app-name
          value: <app-name>
        - name: image-with-tag
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pipeline-shared-data

    - name: test-deploy
      runAfter:
        - kustomize-build
      params:
        - name: app-namespace
          value: <namespace>
        - name: app-name
          value: <app-name>
      taskRef:
        kind: Task
        name: test-deploy
      workspaces:
        - name: source
          workspace: pipeline-shared-data
  workspaces:
    - name: pipeline-shared-data